version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: demo-nodejs
    IMAGE_TAG: "${CODEBUILD_RESOLVED_SOURCE_VERSION}"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - cd app
      - npm ci
      - cd ..
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com)
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo REPO_URI=$REPO_URI
  build:
    commands:
      - echo Running unit tests
      - cd app && npm test || { echo 'Tests failed'; exit 1; }
      - cd ..
      - echo Building Docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"containerName","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
